### ISSUE TITLE
Project Clone

### ISSUE THREAD

**Issue by pixie79** [tmclaugh/suitcase#26]
Hi,

I am just dropping you a note to say thanks for building this project it covers a good base area. I have forked it for our use but we are also looking to keep the fork open so that others can if they wish continue to use it and submit patches or fork from us as well if they wish.
We are looking to remove the Packer dependency as this will enable us to create images with multiple disks and LVM, it will also allow us to create EBS backed HVM AMIs as well. Going forward we will be looking at extending it further to support Microsoft Azure and Google Compute.

You can find our public fork here - https://bitbucket.org/bigdatapartnership/suitcase_testing/overview

Regards

Mark

**Comment by tmclaugh** [comment]
Thank you so much for the kind words!  It started off because we needed anyone on the team to be able to alter and build a new image, I was fiddling with Packer, and I didn't want to write documentation for a complicated build process.  Happy to see this taken in a new direction.

I wave wanted to remove the shell scripts and replace them with ansible or saltstack if that helps with any ideas.
